spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xmmall?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
server:
  port: 4000
mybatis:
  configuration:
    map-underscore-to-camel-case: true